// Mocks generated by Mockito 5.4.6 from annotations
// in fake_store/test/components/products/data/datasources/remote/products_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fake_store/network/model/http/http_route.dart' as _i5;
import 'package:fake_store/common/models/result.dart' as _i4;
import 'package:fake_store/network/router/network_router.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NetworkRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkRouter extends _i1.Mock implements _i2.NetworkRouter {
  MockNetworkRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<T>> fetch<T>(_i5.HttpRoute? route) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [route]),
            returnValue: _i3.Future<_i4.Result<T>>.value(
              _i6.dummyValue<_i4.Result<T>>(
                this,
                Invocation.method(#fetch, [route]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<T>>);
}
