// Mocks generated by Mockito 5.4.6 from annotations
// in fake_store/test/components/shopping_car/presentation/controllers/shopping_cart_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fake_store/components/shopping_cart/domain/models/cart_item.dart'
    as _i4;
import 'package:fake_store/components/shopping_cart/domain/repositories/shopping_cart_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ShoppingCartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingCartRepository extends _i1.Mock
    implements _i2.ShoppingCartRepository {
  MockShoppingCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CartItem>> getCartItems(bool? isExpress) =>
      (super.noSuchMethod(
            Invocation.method(#getCartItems, [isExpress]),
            returnValue: _i3.Future<List<_i4.CartItem>>.value(<_i4.CartItem>[]),
          )
          as _i3.Future<List<_i4.CartItem>>);

  @override
  _i3.Future<void> saveCartItem(_i4.CartItem? item) =>
      (super.noSuchMethod(
            Invocation.method(#saveCartItem, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateQuantity(
    int? productId,
    bool? isExpress,
    int? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [
              productId,
              isExpress,
              quantity,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteCartItem(int? productId, bool? isExpress) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCartItem, [productId, isExpress]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCart(bool? isExpress) =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, [isExpress]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
